# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: Setup VCPKG
description: Sets VCPKG_DEFAULT_TRIPLET and calls lukka/run-vcpkg

inputs:
  arch:
    required: false
    description: Target architecture
    default: x64

runs:
  using: "composite"
  steps:
    - name: Set VCPKG_DEFAULT_TRIPLET
      shell: bash
      run: |
        case ${{ runner.os }} in
        Windows) tripletOs=windows ;;
        Linux) tripletOs=linux ;;
        macOS) tripletOs=osx ;;
        esac
        echo "VCPKG_DEFAULT_TRIPLET=${{ inputs.arch }}-$tripletOs" >> $GITHUB_ENV
    - name: Restore artifacts, or run vcpkg, build and cache artifacts
      uses: lukka/run-vcpkg@v10
      with:
        appendedCacheKey: ${{ env.VCPKG_DEFAULT_TRIPLET }}
        vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
