name: Clang Format

on:
  pull_request_target:
    types: [closed]
    branches:
      - main

jobs:
  format:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      VCPKG_COMMIT_ID: f78f4440df86358575dea65e748a39fdad41eb85
    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest
      - name: Clang format
        uses: DoozyX/clang-format-lint-action@v0.14
        with:
          source: "."
          clangFormatVersion: 14
          inplace: true
      - uses: mattnotmitt/doxygen-action@v1
        name: Build docs
        with:
          working-directory: .
          doxyfile-path: "./Doxyfile"
      - name: Checkout doxybook2
        uses: actions/checkout@v2
        with:
          repository: matusnovak/doxybook2
          path: doxybook2
      - name: Install Doxybook2 deps
        run: |
          vcpkg install --triplet x64-linux $(cat vcpkg.txt)
      - name: Configure doxybook2 cmake and build
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: "CMakeListsTxtBasic"
          cmakeListsTxtPath: "${{ github.workspace }}/doxybook2/CMakeLists.txt"
          cmakeGenerator: UnixMakefiles
          cmakeBuildType: MinSizeRel
          useVcpkgToolchainFile: true
          buildWithCMakeArgs: "--config MinSizeRel"
          buildWithCMake: true
          buildDirectory: "${{ github.workspace }}/doxybook2/build"
      - name: Make engine docs directory if it does not exist
        run: mkdir -p ${{ github.workspace }}/docs/engine
      - name: Build doxybook2 docs
        run: ${{ github.workspace }}/doxybook2/build/src/DoxybookCli/doxybook2 --input ${{ github.workspace }}/doxygen/xml --output ${{ github.workspace }}/docs/engine --config ${{ github.workspace }}/.doxybook/config.json
      - name: Display changed files
        run: git status
      - name: Commit any clang format changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Committing clang-format and engine doc changes"
